### ISSUE TITLE
Entities のリンク置換時、配列を length でソート

### ISSUE THREAD

**Issue by taishi1** [stonetank/Yukiusagi#12]
たとえば `#ex #example` のようなハッシュタグがあり `status.entities.hashtags` において `ex` が先に来た場合、 `example` の `ex` 部分だけが置換されてしまう。  
そこで `status.entities.hashtags` を文字列の length によりソートし、長いものから置換するようにする。

**Comment by pagrus1** [comment]
ついでに重複を削除するとか

**Comment by pagrus1** [comment]
置換後の文字列が、数値文字参照になるようにすれば重複は解決?
